name: bulb
description: BULB İşletme Uygulaması.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+19

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.6
  image_cropper: ^1.4.0
  font_awesome_flutter: ^9.0.0
  cool_alert: ^1.1.0
  geolocator: ^7.0.3
  uuid: ^3.0.4
  provider: ^5.0.0
  image_picker: ^0.8.0+3
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  permission_handler: ^8.0.1
  url_launcher: ^6.0.7
  firebase_storage: ^8.1.1
  cloud_firestore: ^2.2.1
  firebase_auth: ^1.3.0
  firebase_core: ^1.2.1
  firebase_messaging: ^10.0.1
  google_sign_in: ^5.0.4
  geoflutterfire: ^3.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400
    - family: Armatic
      fonts:
        - asset: assets/fonts/AmaticSC-Regular.ttf
          weight: 400
