name: papape_store
description: PaPaPe İşletme Uygulaması.

publish_to: 'none'

version: 0.1.0+37

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.11
  image_cropper: ^1.4.0
  font_awesome_flutter: ^9.1.0
  cool_alert: ^1.1.0
  geolocator: ^7.2.0+1
  uuid: ^3.0.5
  provider: ^6.0.1
  image_picker: ^0.8.0+3
  intl: ^0.17.0
  permission_handler: ^8.2.5
  url_launcher: ^6.0.12
  firebase_storage: ^8.1.1
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  google_sign_in: ^5.1.1
  geoflutterfire: ^3.0.1
  flutter_speed_dial: ^4.4.0+2
  curved_navigation_bar: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^0.1.3
  flutter_native_splash: ^1.2.3
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/adaptive_icon_background.png"
  adaptive_icon_foreground: "assets/images/adaptive_icon_foreground.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/splash_logo.png
    - assets/images/logo.png

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400
    - family: Armatic
      fonts:
        - asset: assets/fonts/AmaticSC-Regular.ttf
          weight: 400
